stages:
  - build
  - compress

Build_Go:
  image: golang:latest
  stage: build
  script:
    - go build -ldflags="-s -w" -v -o latexautoinstaller
  artifacts:
    expire_in: 2 days
    paths:
      - "./latexautoinstaller*"

Compress_upx:
  image: fjolsvin/upx
  stage: compress
  dependencies:
    - Build_Go
  script:
    - upx --ultra-brute -v --no-progress -o latexautoinstaller-upx latexautoinstaller
  artifacts:
    expire_in: 2 days
    paths:
      - "./latexautoinstaller-upx*"